version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - odoo_db:/var/lib/mysql
    networks:
      - odoo-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo_backend:
    image: odoobackend:latest
    container_name: odoo_backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - odoo-network
    restart: always

volumes:
  odoo_db:

networks:
  odoo-network:
    driver: bridge